# Generated by Django 2.0.6 on 2018-09-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_aadhar', models.CharField(max_length=12, unique=True)),
                ('c_name', models.CharField(max_length=100)),
                ('c_dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(max_length=10, unique=True)),
                ('h_aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_c_id', to='mainapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Sugar', 'Sugar'), ('Oil', 'Oil'), ('Ragi', 'Ragi')], max_length=20)),
                ('i_quantity', models.IntegerField()),
                ('i_fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_fam_id', to='mainapp.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('p_id', models.CharField(max_length=10)),
                ('p_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('u_address', models.CharField(max_length=300)),
                ('u_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('v_id', models.CharField(max_length=10)),
                ('v_address', models.CharField(max_length=200)),
                ('v_description', models.CharField(max_length=300)),
                ('v_phoneNum', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='packaging',
            name='p_UnitName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_id', to='mainapp.Unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_pack_id', to='mainapp.Packaging'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_ven_id', to='mainapp.Vendor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='c_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_fam_id', to='mainapp.Family'),
        ),
    ]
