# Generated by Django 2.0.6 on 2018-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='h_aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
