# Generated by Django 2.0.6 on 2018-09-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180928_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='h_aadhar',
        ),
        migrations.AlterField(
            model_name='item',
            name='i_name',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Sugar', 'Sugar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='i_quantity',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('4', '4')]),
        ),
    ]
