# Generated by Django 2.0.6 on 2018-09-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180929_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='i_fam',
        ),
    ]
